---
version: '3.8'

networks:
  backend-network:
  proxy-net:

volumes:
  db-volume:
  cache-volume:

services:
  spades-db:
    image: centos/postgresql-12-centos7
    restart: on-failure
    volumes:
      - db-volume:/var/lib/postgresql/data
    networks:
      - backend-network
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "spades"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRESQL_DATABASE: spades
      POSTGRESQL_USER: spades
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}

  spades-cache:
    image: centos/redis-5-centos7
    restart: on-failure
    volumes:
      - cache-volume:/var/lib/redis/data
    networks:
      - backend-network
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

  spades:
    build: .
    restart: on-failure
    depends_on:
      - spades-db
      - spades-cache
    # links:
    #   - spades-db:spades-db
    networks:
      - backend-network
      - proxy-net
    expose:
      - 8080
    environment:
      POSTGRESQL_HOST: spades-db
      POSTGRESQL_USER: spades
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
      REDIS_HOST: spades-cache
      REDIS_PASSWORD: ${REDIS_PASSWORD}

  proxy:
    build: nginx/
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:z
      - ./nginx/certs:/etc/nginx/ssl:z
    depends_on:
      - spades
    networks:
      - proxy-net
    ports:
      - '80:80'
      - '443:443'
