---
version: '3.8'

networks:
  postgres-net:
  redis-net:
  # keycloak-net:

volumes:
  postgres-datastore:
  redis-datastore:
  # keycloak-datastore:

services:
  spades-db:
    image: centos/postgresql-12-centos7
    volumes:
      - postgres-datastore:/var/lib/postgresql/data
    networks:
      - postgres-net
    ports:
      - '5432:5432'
    environment:
      POSTGRESQL_DATABASE: spades
      POSTGRESQL_USER: spades
      POSTGRESQL_PASSWORD: password

  redis:
    image: centos/redis-5-centos7
    volumes:
      - redis-datastore:/var/lib/redis/data
    networks:
      - redis-net
    ports:
      - '6379:6379'
    environment:
      REDIS_PASSWORD: password

#   keycloak-db:
#     image: postgres:9.6
#     volumes:
#       - keycloak-datastore:/var/lib/postresql/data
#     networks:
#       - keycloak-net
#     ports:
#       - '25432:5432'
#     environment:
#       REDIS_DB: keycloak
#       REDIS_USER: keycloak
#       REDIS_PASSWORD: password
#
#   keycloak:
#     image: jboss/keycloak:4.5.0.Final
#     depends_on:
#       - keycloak-db
#     networks:
#       - keycloak-net
#     ports:
#       - '8180:8080'
#     environment:
#       DB_VENDOR: POSTGRES
#       DB_ADDR: keycloak-db
#       DB_PORT: 5432
#       DB_DATABASE: keycloak
#       DB_USER: keycloak
#       DB_PASSWORD: password
#       KEYCLOAK_USER: admin
#       KEYCLOAK_PASSWORD: admin
