---
version: '3.8'

networks:
  backend-network:
  # db-net:
  # cache-net:
  proxy-net:

volumes:
  db-volume:
  cache-volume:

services:
  spades-db:
    image: centos/postgresql-12-centos7
    volumes:
      - db-volume:/var/lib/postgresql/data
    networks:
      # - db-net
      - backend-network
    expose:
      - 5432
    ports:
      - '5432:5432'
    environment:
      POSTGRESQL_DATABASE: spades
      POSTGRESQL_USER: spades
      POSTGRESQL_PASSWORD: password

  spades-cache:
    image: centos/redis-5-centos7
    volumes:
      - cache-volume:/var/lib/redis/data
    networks:
      # - cache-net
      - backend-network
    ports:
      - '6379:6379'
    environment:
      REDIS_PASSWORD: password

  spades:
    build: .
    depends_on:
      - spades-db
      - spades-cache
    links:
      - spades-db:spades-db
    networks:
      - backend-network
      # - db-net
      # - cache-net
      - proxy-net
    ports:
      - '8080:8080'
    environment:
      POSTGRESQL_HOST: spades-db
      POSTGRESQL_USER: spades
      POSTGRESQL_PASSWORD: password
      REDIS_HOST: spades-cache
      REDIS_PASSWORD: password

#   proxy:
#     build: nginx
#     image: nginx:latest
#     depends_on: spades
#     networks:
#       - proxy-net
#     ports:
#       - '80:80'
#       - '443:443'
#     environment:
#       POSTGRESQL_HOST: spades-db
#       REDIS_HOST: redis
#       REDIS_PASSWORD: ${WEBAPP_REDIS_PASSWORD:-password}
