---
name: Python package
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v2
      - name: "Set up Python ${{ matrix.python-version }}"
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python-version }}"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv install --dev
      - name: Lint
        run: |
          pipenv run workflow-tools style.sort-headers.run --check
          pipenv run workflow-tools style.format.run --check
          pipenv run workflow-tools sca.lint.run
          pipenv run workflow-tools sca.type-checking.run
      - name: Perform tests
        run: pipenv run workflow-tools qa.unit-test.run
      - name: Perform security checks
        run: |
          pipenv run workflow-tools sec.sast.run
          pipenv run workflow-tools sec.dependency-scan.run
      - name: Lint documentation
        run: |
          pipenv run workflow-tools docs.style
          pipenv run workflow-tools docs.coverage
      - name: Perform documentation build
        run: pipenv run workflow-tools docs.site.build
